name: Build Mega Parser CLI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Mega Parser CLI (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          bun-linux-x64,
          bun-linux-arm64,
          bun-windows-x64,
          bun-darwin-x64,
          bun-darwin-arm64
        ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build mega-parser package
        run: |
          cd packages/mega-parser
          bun run build

      - name: Build mega-parser CLI
        run: |
          cd packages/cli
          bun build ./src/index.ts --compile --target=${{ matrix.target }} --minify --sourcemap --outfile mega-parser-${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mega-parser-${{ matrix.target }}
          path: packages/cli/mega-parser-${{ matrix.target }}
          if-no-files-found: error
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          VERSION=$(node -p "require('./packages/cli/package.json').version")
          echo "version=v${VERSION}" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: mega-parser-${{ steps.get_version.outputs.version }}
          name: Mega Parser CLI ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            artifacts/mega-parser-bun-linux-x64/mega-parser-bun-linux-x64
            artifacts/mega-parser-bun-linux-arm64/mega-parser-bun-linux-arm64
            artifacts/mega-parser-bun-windows-x64/mega-parser-bun-windows-x64
            artifacts/mega-parser-bun-darwin-x64/mega-parser-bun-darwin-x64
            artifacts/mega-parser-bun-darwin-arm64/mega-parser-bun-darwin-arm64 