name: Build Sonar Analysis CLI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Sonar Analysis CLI (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          bun-linux-x64,
          bun-linux-arm64,
          bun-windows-x64,
          bun-darwin-x64,
          bun-darwin-arm64
        ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build sonar-analysis CLI
        run: |
          cd packages/automated-sonar-analysis
          bun run build
          bun build ./dist/index.js --compile --target=${{ matrix.target }} --minify --sourcemap --outfile sonar-analysis-${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sonar-analysis-${{ matrix.target }}
          path: packages/automated-sonar-analysis/sonar-analysis-${{ matrix.target }}
          if-no-files-found: error
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          VERSION=$(node -p "require('./packages/automated-sonar-analysis/package.json').version")
          echo "version=v${VERSION}" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: sonar-analysis-${{ steps.get_version.outputs.version }}
          name: Sonar Analysis CLI ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            artifacts/sonar-analysis-bun-linux-x64/sonar-analysis-bun-linux-x64
            artifacts/sonar-analysis-bun-linux-arm64/sonar-analysis-bun-linux-arm64
            artifacts/sonar-analysis-bun-windows-x64/sonar-analysis-bun-windows-x64
            artifacts/sonar-analysis-bun-darwin-x64/sonar-analysis-bun-darwin-x64
            artifacts/sonar-analysis-bun-darwin-arm64/sonar-analysis-bun-darwin-arm64 