name: Build Sonar Analysis CLI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Sonar Analysis CLI (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          bun-linux-x64,
          bun-linux-arm64,
          bun-windows-x64,
          bun-darwin-x64,
          bun-darwin-arm64
        ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build sonar-analysis CLI
        run: |
          cd packages/automated-sonar-analysis
          bun run build
          bun build ./dist/index.js --compile --target=${{ matrix.target }} --minify --sourcemap --outfile sonar-analysis-${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sonar-analysis-${{ matrix.target }}
          path: packages/automated-sonar-analysis/sonar-analysis-${{ matrix.target }}
          if-no-files-found: error
          retention-days: 1 